# Generated by Django 4.1.1 on 2022-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Reg',
        ),
    ]
